-- ============================================
-- PharmaSmart - Script 03
-- Creación de Índices
-- Ejecutar como PHARMA_USER
-- Autor: Luis Alberto Ariza Villamizar
-- Universidad Popular del Cesar
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

PROMPT ========================================
PROMPT Creando índices...
PROMPT ========================================

-- Índices para LOTES (FEFO)
CREATE INDEX IDX_LOTES_PRODUCTO ON LOTES(ID_PRODUCTO);
CREATE INDEX IDX_LOTES_VENCIMIENTO ON LOTES(FECHA_VENCIMIENTO);
CREATE INDEX IDX_LOTES_ESTADO ON LOTES(ESTADO);
-- Índice compuesto optimizado para FEFO
CREATE INDEX IDX_LOTES_FEFO ON LOTES(ID_PRODUCTO, ESTADO, FECHA_VENCIMIENTO, CANTIDAD_ACTUAL);

-- Índices para VENTAS
CREATE INDEX IDX_VENTAS_USUARIO ON VENTAS(ID_USUARIO);
CREATE INDEX IDX_VENTAS_FECHA ON VENTAS(FECHA_VENTA);
CREATE INDEX IDX_VENTAS_CLIENTE ON VENTAS(ID_CLIENTE);
CREATE INDEX IDX_VENTAS_ESTADO ON VENTAS(ESTADO, FECHA_VENTA);

-- Índices para DETALLES_VENTAS
CREATE INDEX IDX_DETALLES_VENTA ON DETALLES_VENTAS(ID_VENTA);
CREATE INDEX IDX_DETALLES_LOTE ON DETALLES_VENTAS(ID_LOTE);
CREATE INDEX IDX_DETALLES_PRODUCTO ON DETALLES_VENTAS(ID_PRODUCTO);

-- Índices para AJUSTES_INVENTARIO
CREATE INDEX IDX_AJUSTES_LOTE ON AJUSTES_INVENTARIO(ID_LOTE);
CREATE INDEX IDX_AJUSTES_RESPONSABLE ON AJUSTES_INVENTARIO(ID_RESPONSABLE);
CREATE INDEX IDX_AJUSTES_FECHA ON AJUSTES_INVENTARIO(FECHA_AJUSTE);

-- Índices para HISTORIAL_PARAMETROS
CREATE INDEX IDX_HP_CLAVE ON HISTORIAL_PARAMETROS(CLAVE_PARAMETRO);
CREATE INDEX IDX_HP_FECHA ON HISTORIAL_PARAMETROS(FECHA_CAMBIO);
CREATE INDEX IDX_HP_USUARIO ON HISTORIAL_PARAMETROS(ID_USUARIO);

-- Índices para HISTORIAL_DESCUENTOS
CREATE INDEX IDX_HD_PRODUCTO ON HISTORIAL_DESCUENTOS(ID_PRODUCTO);
CREATE INDEX IDX_HD_USUARIO ON HISTORIAL_DESCUENTOS(ID_USUARIO);

-- Índices para ALERTAS_INFLACION
CREATE INDEX IDX_AI_PRODUCTO ON ALERTAS_INFLACION(ID_PRODUCTO);
CREATE INDEX IDX_AI_ESTADO ON ALERTAS_INFLACION(ESTADO);

-- Índices para ALERTAS_FIDELIZACION
CREATE INDEX IDX_AF_CLIENTE ON ALERTAS_FIDELIZACION(ID_CLIENTE);
CREATE INDEX IDX_AF_ESTADO ON ALERTAS_FIDELIZACION(ESTADO);

-- Índices para CLIENTES
CREATE INDEX IDX_CLIENTES_CHAT ON CLIENTES(CHAT_ID);

COMMIT;

PROMPT ========================================
PROMPT Índices creados: 24
PROMPT ========================================
EXIT;